# Generated by Erlang.mk. Edit at your own risk!

src/average_calc_task.erl:: src/regional_server_app.erl; @touch $@
src/toppage_h.erl:: src/average_calc_task.erl; @touch $@

COMPILE_FIRST += regional_server_app average_calc_task
